# This file holds the information for the supported models for each wiki context.
# This information was extracted from ORES at the time this application was deployed.
# from the url: https://ores.wikimedia.org/v3/scores
arwiki:
  models:
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
bnwiki:
  models:
    reverted:
      version: 0.5.0
bswiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
cawiki:
  models:
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
cswiki:
  models:
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.6.0
    goodfaith:
      version: 0.6.0
dewiki:
  models:
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
elwiki:
  models:
    reverted:
      version: 0.5.0
enwiki:
  models:
    articlequality:
      version: 0.9.2
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.5.1
    draftquality:
      version: 0.2.1
    drafttopic:
      version: 1.3.0
    goodfaith:
      version: 0.5.1
    wp10:
      version: 0.9.2
enwiktionary:
  models:
    reverted:
      version: 0.5.0
eswiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
eswikibooks:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
eswikiquote:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
etwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
euwiki:
  models:
    articlequality:
      version: 0.8.1
    articletopic:
      version: 1.4.0
    wp10:
      version: 0.8.1
fakewiki:
  models:
    damaging:
      version: 0.0.3
    goodfaith:
      version: 0.0.3
fawiki:
  models:
    articlequality:
      version: 0.9.0
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
    wp10:
      version: 0.9.0
fiwiki:
  models:
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
frwiki:
  models:
    articlequality:
      version: 0.8.0
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
    wp10:
      version: 0.8.0
frwikisource:
  models:
    pagelevel:
      version: 0.3.0
glwiki:
  models:
    articlequality:
      version: 0.8.0
    reverted:
      version: 0.5.0
hewiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
hiwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
hrwiki:
  models:
    reverted:
      version: 0.5.0
huwiki:
  models:
    articletopic:
      version: 1.4.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
hywiki:
  models:
    articletopic:
      version: 1.4.0
idwiki:
  models:
    reverted:
      version: 0.5.0
iswiki:
  models:
    reverted:
      version: 0.5.0
itwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
jawiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
kowiki:
  models:
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
lvwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
nlwiki:
  models:
    articlequality:
      version: 0.9.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
nowiki:
  models:
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
plwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
ptwiki:
  models:
    articlequality:
      version: 0.8.0
    damaging:
      version: 0.5.1
    draftquality:
      version: 0.2.1
    goodfaith:
      version: 0.5.1
rowiki:
  models:
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
ruwiki:
  models:
    articlequality:
      version: 0.8.0
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
    wp10:
      version: 0.8.0
simplewiki:
  models:
    articlequality:
      version: 0.9.2
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.5.1
    draftquality:
      version: 0.2.1
    goodfaith:
      version: 0.5.1
    wp10:
      version: 0.9.2
sqwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
srwiki:
  models:
    articletopic:
      version: 1.4.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
svwiki:
  models:
    articlequality:
      version: 0.8.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
tawiki:
  models:
    reverted:
      version: 0.5.0
testwiki:
  models:
    articlequality:
      version: 0.9.2
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.0.3
    draftquality:
      version: 0.2.1
    drafttopic:
      version: 1.3.0
    goodfaith:
      version: 0.0.3
    reverted:
      version: 0.0.3
    wp10:
      version: 0.9.2
trwiki:
  models:
    articlequality:
      version: 0.8.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
    wp10:
      version: 0.8.0
ukwiki:
  models:
    articlequality:
      version: 0.8.0
    articletopic:
      version: 1.3.0
    damaging:
      version: 0.5.1
    goodfaith:
      version: 0.5.1
viwiki:
  models:
    articletopic:
      version: 1.4.0
    reverted:
      version: 0.5.0
wikidatawiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
    itemquality:
      version: 0.5.0
    itemtopic:
      version: 1.2.0
zhwiki:
  models:
    damaging:
      version: 0.5.0
    goodfaith:
      version: 0.5.0
