"""Artifact sinks: where generated bytes go (Spike 2, intake open question #3).

The intake left blob-write ownership open: does the compute function write
to the blob store and return URIs, or return bytes for the invoking layer
to write? This module makes the answer "we support both, your call" by
putting the choice behind one interface selected by config:

* ``inline`` (default): artifacts return as ``bytes_b64`` in the response.
  Keeps us unblocked while storage does not exist; LAC-native (the cache
  stores what the compute function returns).
* ``file``: artifacts are written under BLOB_SINK_DIR with the canonical
  key layout and the response carries ``blob_uri`` (file://...). Used by
  the Phase 4 pilot so 50 articles of audio do not travel as base64
  through the driver script; also the local stand-in for object storage.
* ``s3``: the write-to-object-storage mode, interface-complete but
  unconfigured until Data Persistence provisions the Swift/S3 PoC bucket
  and credentials. Selecting it without endpoint config fails loudly at
  STARTUP, not at first write.

Key layout (the revision-scoped schema from the intake doc):
    {wiki_id}/{page_id}/{rev_id}/{section_id}.{ext}
Deterministic from the request, so re-writes are idempotent overwrites of
identical bytes (golden determinism, verified in Phase 2, is what makes
that safe).
"""

import base64
import logging
from pathlib import Path

from tts_generator.config import BLOB_SINK, BLOB_SINK_DIR, S3_BUCKET, S3_ENDPOINT

logger = logging.getLogger(__name__)

_EXT = {
    "audio_opus": "opus",
    "audio_mp3": "mp3",
    "captions_vtt": "vtt",
    "timestamps_json": "json",
    "audio_pcm_s16le": "pcm",
}


def artifact_key(
    wiki_id: str, page_id: int, rev_id: int, section_id: str, artifact_type: str
) -> str:
    return f"{wiki_id}/{page_id}/{rev_id}/{section_id}.{_EXT[artifact_type]}"


class InlineSink:
    """Return bytes in the response body (bytes_b64)."""

    mode = "inline"

    def store(self, key: str, data: bytes, media_type: str) -> dict:
        return {"bytes_b64": base64.b64encode(data).decode("ascii")}


class FileSink:
    """Write under a local directory; return a file:// blob_uri."""

    mode = "file"

    def __init__(self, root: str):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def store(self, key: str, data: bytes, media_type: str) -> dict:
        path = self.root / key
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_bytes(data)  # atomic publish: partial writes never visible
        tmp.rename(path)
        return {"blob_uri": path.as_uri(), "size_bytes": len(data)}


class S3Sink:
    """Object-storage write mode. Interface-complete; wiring lands when
    Data Persistence provisions the bucket. Kept as a stub deliberately:
    the boto3 dependency and credential plumbing should arrive together
    with a real endpoint to test against, not before."""

    mode = "s3"

    def __init__(self, endpoint: str, bucket: str):
        if not endpoint or not bucket:
            raise RuntimeError(
                "BLOB_SINK=s3 requires TTS_GEN_S3_ENDPOINT and TTS_GEN_S3_BUCKET "
                "(Data Persistence PoC bucket not provisioned yet? use "
                "inline or file)"
            )
        self.endpoint, self.bucket = endpoint, bucket
        raise NotImplementedError(
            "S3 sink wiring lands with the Data Persistence PoC bucket"
        )

    def store(self, key: str, data: bytes, media_type: str) -> dict:  # pragma: no cover
        raise NotImplementedError


def build_sink():
    """Construct the configured sink. Called once at service startup so a
    misconfigured sink fails the deploy, not the first request."""
    if BLOB_SINK == "inline":
        return InlineSink()
    if BLOB_SINK == "file":
        return FileSink(BLOB_SINK_DIR)
    if BLOB_SINK == "s3":
        return S3Sink(S3_ENDPOINT, S3_BUCKET)
    raise RuntimeError(f"Unknown BLOB_SINK {BLOB_SINK!r} (inline|file|s3)")
