"""Artifact sinks: where generated bytes go (Spike 2, intake open question #3).

The intake left blob-write ownership open: does the compute function write
to the blob store and return URIs, or return bytes for the invoking layer
to write? This module makes the answer "we support both, your call" by
putting the choice behind one interface selected by config:

* ``inline`` (default): artifacts return as ``bytes_b64`` in the response.
  Keeps us unblocked while storage does not exist; LAC-native (the cache
  stores what the compute function returns).
* ``file``: artifacts are written under BLOB_SINK_DIR with the canonical
  key layout and the response carries ``blob_uri`` (file://...). Used by
  the Phase 4 pilot so 50 articles of audio do not travel as base64
  through the driver script; also the local stand-in for object storage.
* ``s3``: writes to S3-compatible object storage (thanos-swift or any
  S3 endpoint; Swift's s3api middleware exposes the S3 protocol). boto3 with
  path-style addressing (required by Swift and MinIO), credentials from
  the standard AWS env vars (mounted from a Kubernetes Secret following
  the swift-s3-credentials pattern). Misconfiguration (missing config,
  unreachable endpoint, absent bucket, bad credentials) fails loudly at
  STARTUP via a head_bucket probe, not at first write.

Key layout (the revision-scoped schema from the intake doc):
    {wiki_id}/{page_id}/{rev_id}/{section_id}.{ext}
Deterministic from the request, so re-writes are idempotent overwrites of
identical bytes (golden determinism, verified in Phase 2, is what makes
that safe).
"""

import base64
import logging
from pathlib import Path

from tts_generator.config import (
    BLOB_SINK,
    BLOB_SINK_DIR,
    S3_BUCKET,
    S3_ENDPOINT,
    S3_REGION,
)

logger = logging.getLogger(__name__)


class SinkWriteError(Exception):
    """A blob write failed at generation time (transient: the caller may
    retry the whole request; generation is idempotent). Mapped to the
    blob_write_error taxonomy code by the service layer."""


_EXT = {
    "audio_opus": "opus",
    "audio_mp3": "mp3",
    "captions_vtt": "vtt",
    "timestamps_json": "json",
    "audio_pcm_s16le": "pcm",
}


def artifact_key(
    wiki_id: str, page_id: int, rev_id: int, section_id: str, artifact_type: str
) -> str:
    return f"{wiki_id}/{page_id}/{rev_id}/{section_id}.{_EXT[artifact_type]}"


class InlineSink:
    """Return bytes in the response body (bytes_b64)."""

    mode = "inline"

    def store(self, key: str, data: bytes, media_type: str) -> dict:
        return {"bytes_b64": base64.b64encode(data).decode("ascii")}


class FileSink:
    """Write under a local directory; return a file:// blob_uri."""

    mode = "file"

    def __init__(self, root: str):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def store(self, key: str, data: bytes, media_type: str) -> dict:
        path = self.root / key
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_bytes(data)  # atomic publish: partial writes never visible
        tmp.rename(path)
        return {"blob_uri": path.as_uri(), "size_bytes": len(data)}


class S3Sink:
    """Write to S3-compatible object storage; return an s3:// blob_uri.

    Design notes, hard-won against WMF infrastructure:

    * PATH-STYLE addressing is mandatory: Swift's s3api middleware (and
      MinIO) do not serve virtual-host bucket URLs. Same flag every other
      WMF service sets against thanos-swift.
    * Credentials come from the standard AWS env vars, which boto3 reads
      natively; no credential handling in this code. In deployment they
      are mounted from a Kubernetes Secret (swift-s3-credentials pattern).
    * The startup head_bucket probe makes every misconfiguration class
      (endpoint, credentials, bucket, egress policy) fail the DEPLOY with
      an actionable message, not request #1.
    * put_object is atomic per object, so there is no tmp+rename dance to
      replicate; overwrite idempotence holds for audio artifacts (byte-
      deterministic transcode) and is tolerated for timing sidecars,
      which may differ by one CTC frame across regenerations.
    * botocore's own retries cover transient endpoint blips; a write that
      still fails raises SinkWriteError, surfaced by the service as the
      transient blob_write_error taxonomy code.
    """

    mode = "s3"

    def __init__(self, endpoint: str, bucket: str, region: str = S3_REGION):
        if not endpoint or not bucket:
            raise RuntimeError(
                "BLOB_SINK=s3 requires TTS_GEN_S3_ENDPOINT and TTS_GEN_S3_BUCKET "
                "(Data Persistence PoC bucket not provisioned yet? use "
                "inline or file)"
            )
        try:
            import boto3
            from botocore.config import Config as BotoConfig
        except ImportError as e:
            raise RuntimeError(
                "BLOB_SINK=s3 requires boto3 (in requirements.txt for the "
                "production image; pip install boto3 for local dev)"
            ) from e

        self.endpoint, self.bucket = endpoint, bucket
        self._client = boto3.client(
            "s3",
            endpoint_url=endpoint,
            region_name=region,
            config=BotoConfig(
                s3={"addressing_style": "path"},
                retries={"max_attempts": 3, "mode": "standard"},
                connect_timeout=10,
                read_timeout=60,
            ),
        )
        # Fail the deploy, not request #1: one cheap probe verifies
        # endpoint reachability, credentials, and bucket existence.
        try:
            self._client.head_bucket(Bucket=bucket)
        except Exception as e:
            raise RuntimeError(
                f"S3 sink startup check failed (endpoint={endpoint!r}, "
                f"bucket={bucket!r}): {e}. Check TTS_GEN_S3_ENDPOINT / "
                "TTS_GEN_S3_BUCKET, the AWS_ACCESS_KEY_ID / "
                "AWS_SECRET_ACCESS_KEY secret, and the egress network "
                "policy for the object-storage frontend."
            ) from e
        logger.info("S3 sink ready: %s bucket=%s (path-style)", endpoint, bucket)

    def store(self, key: str, data: bytes, media_type: str) -> dict:
        from botocore.exceptions import BotoCoreError, ClientError

        try:
            self._client.put_object(
                Bucket=self.bucket, Key=key, Body=data, ContentType=media_type
            )
        except (ClientError, BotoCoreError) as e:
            raise SinkWriteError(f"S3 put_object failed for {key!r}: {e}") from e
        return {"blob_uri": f"s3://{self.bucket}/{key}", "size_bytes": len(data)}


def build_sink():
    """Construct the configured sink. Called once at service startup so a
    misconfigured sink fails the deploy, not the first request."""
    if BLOB_SINK == "inline":
        return InlineSink()
    if BLOB_SINK == "file":
        return FileSink(BLOB_SINK_DIR)
    if BLOB_SINK == "s3":
        return S3Sink(S3_ENDPOINT, S3_BUCKET)
    raise RuntimeError(f"Unknown BLOB_SINK {BLOB_SINK!r} (inline|file|s3)")
