# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lambda.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0clambda.proto\x12\x06lambda"=\n\rLambdaRequest\x12\x0c\n\x04wiki\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x03\x12\x10\n\x08revision\x18\x03 \x01(\x03"\x8a\x01\n\x0eLambdaResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x36\n\x08metadata\x18\x02 \x03(\x0b\x32$.lambda.LambdaResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32M\n\rLambdaService\x12<\n\x0bGetArtifact\x12\x15.lambda.LambdaRequest\x1a\x16.lambda.LambdaResponseB\tZ\x07./protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lambda_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\007./proto"
    _globals["_LAMBDARESPONSE_METADATAENTRY"]._options = None
    _globals["_LAMBDARESPONSE_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_LAMBDAREQUEST"]._serialized_start = 24
    _globals["_LAMBDAREQUEST"]._serialized_end = 85
    _globals["_LAMBDARESPONSE"]._serialized_start = 88
    _globals["_LAMBDARESPONSE"]._serialized_end = 226
    _globals["_LAMBDARESPONSE_METADATAENTRY"]._serialized_start = 179
    _globals["_LAMBDARESPONSE_METADATAENTRY"]._serialized_end = 226
    _globals["_LAMBDASERVICE"]._serialized_start = 228
    _globals["_LAMBDASERVICE"]._serialized_end = 305
# @@protoc_insertion_point(module_scope)
