# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import lambda_pb2 as lambda__pb2


class LambdaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtifact = channel.unary_unary(
            "/lambda.LambdaService/GetArtifact",
            request_serializer=lambda__pb2.LambdaRequest.SerializeToString,
            response_deserializer=lambda__pb2.LambdaResponse.FromString,
        )


class LambdaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LambdaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.GetArtifact,
            request_deserializer=lambda__pb2.LambdaRequest.FromString,
            response_serializer=lambda__pb2.LambdaResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "lambda.LambdaService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class LambdaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lambda.LambdaService/GetArtifact",
            lambda__pb2.LambdaRequest.SerializeToString,
            lambda__pb2.LambdaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
