pipelines:
  editquality:
    directory: revscoring/editquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            name: '${setup.project}-editquality'
            tags: [stable]
  articlequality:
    directory: revscoring/articlequality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            name: '${setup.project}-articlequality'
            tags: [stable]
  draftquality:
    directory: revscoring/draftquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            name: '${setup.project}-draftquality'
            tags: [stable]
  topic:
    directory: revscoring/topic
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            name: '${setup.project}-topic'
            tags: [stable]
