pipelines:
  editquality:
    directory: revscoring/editquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            name: '${setup.project}-editquality'
            tags: [stable]
