pipelines:
  enwiki-goodfaith:
    blubberfile: blubber.yaml
    directory: revscoring/editquality/
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image: true
            tags: [stable]
