pipelines:
  outlink:
    blubberfile: outlink/blubber.yaml
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  outlink-publish:
    blubberfile: outlink/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-outlink'
            tags: [stable]

  revertrisk:
    blubberfile: revertrisk/revertrisk.yaml
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  revertrisk-publish:
    blubberfile: revertrisk/revertrisk.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-revertrisk'
            tags: [stable]

  revertrisk-multilingual-publish:
    blubberfile: revertrisk/multilingual.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-revertrisk-multilingual'
            tags: [stable]

  revertrisk-wikidata-publish:
    blubberfile: revertrisk/wikidata.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-revertrisk-wikidata'
            tags: [stable]

  revscoring-publish:
    blubberfile: revscoring/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-revscoring'
            tags: [stable]

  ores-legacy-publish:
    blubberfile: ores-legacy/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-ores-legacy'
            tags: [stable]

  llm-publish:
    blubberfile: llm/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-llm'
            tags: [stable]

  readability-publish:
    blubberfile: readability/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-readability'
            tags: [stable]

  langid-publish:
    blubberfile: langid/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-langid'
            tags: [stable]

  article-descriptions-publish:
    blubberfile: article_descriptions/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-article-descriptions'
            tags: [stable]

  huggingface-publish:
    blubberfile: huggingface/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-huggingface'
            tags: [stable]

  logo-detection-publish:
    blubberfile: logo_detection/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-logo-detection'
            tags: [stable]

  articlequality-publish:
    blubberfile: articlequality/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-articlequality'
            tags: [stable]

  reference-quality-publish:
    blubberfile: reference_quality/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-reference-quality'
            tags: [stable]

  article-country-publish:
    blubberfile: article_country/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-article-country'
            tags: [stable]

  edit-check:
    blubberfile: edit_check/blubber.yaml
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  edit-check-publish:
    blubberfile: edit_check/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-edit-check'
            tags: [stable]

  pre-commit-check:
    blubberfile: pre-commit-check/blubber.yaml
    stages:
      - name: run-test
        build: test
        run: true
