pipelines:
  editquality:
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  editquality-publish:
    blubberfile: editquality/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-editquality'
            tags: [stable]

  articlequality:
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  articlequality-publish:
    blubberfile: articlequality/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-articlequality'
            tags: [stable]

  draftquality:
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  draftquality-publish:
    blubberfile: draftquality/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-draftquality'
            tags: [stable]

  topic:
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  topic-publish:
    blubberfile: topic/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-topic'
            tags: [stable]

  outlink:
    blubberfile: outlink/blubber.yaml
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  outlink-publish:
    blubberfile: outlink/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-outlink'
            tags: [stable]

  outlink-transformer:
    blubberfile: outlink/transformer.yaml
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  outlink-transformer-publish:
    blubberfile: outlink/transformer.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-outlink-transformer'
            tags: [stable]

  nsfw:
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  nsfw-publish:
    blubberfile: nsfw/blubber.yaml
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-nsfw'
            tags: [stable]
