pipelines:
  editquality:
    directory: revscoring/editquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  editquality-publish:
    blubberfile: editquality/blubber.yaml
    directory: revscoring/editquality
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-editquality'
            tags: [stable]

  editquality-transformer:
    blubberfile: editquality/transformer.yaml
    directory: revscoring/editquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  editquality-transformer-publish:
    blubberfile: editquality/transformer.yaml
    directory: revscoring/editquality
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-editquality-transformer'
            tags: [stable]

  articlequality:
    directory: revscoring/articlequality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  articlequality-publish:
    blubberfile: articlequality/blubber.yaml
    directory: revscoring/articlequality
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-articlequality'
            tags: [stable]

  articlequality-transformer:
    blubberfile: articlequality/transformer.yaml
    directory: revscoring/articlequality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  articlequality-transformer-publish:
    blubberfile: articlequality/transformer.yaml
    directory: revscoring/articlequality
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-articlequality-transformer'
            tags: [stable]

  draftquality:
    directory: revscoring/draftquality
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  draftquality-publish:
    blubberfile: draftquality/blubber.yaml
    directory: revscoring/draftquality
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-draftquality'
            tags: [stable]

  topic:
    directory: revscoring/topic
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  topic-publish:
    blubberfile: topic/blubber.yaml
    directory: revscoring/topic
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-topic'
            tags: [stable]

  outlink:
    blubberfile: outlink/blubber.yaml
    directory: outlink-topic-model
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  outlink-publish:
    blubberfile: outlink/blubber.yaml
    directory: outlink-topic-model
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-outlink'
            tags: [stable]

  outlink-transformer:
    blubberfile: outlink/transformer.yaml
    directory: outlink-topic-model
    stages:
      - name: run-test
        build: test
        run: true
      - name: production
        build: production

  outlink-transformer-publish:
    blubberfile: outlink/transformer.yaml
    directory: outlink-topic-model
    stages:
      - name: publish
        build: production
        publish:
          image:
            name: '${setup.project}-outlink-transformer'
            tags: [stable]
