apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: enwiki-goodfaith
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    controller-tools.k8s.io: "1.0"
spec:
  default:
    predictor:
      custom:
        container:
          image: accraze/kfserving-custom-model
          name: enwiki-goodfaith

