apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: outlink-topic-model
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    controller-tools.k8s.io: "1.0"
spec:
  default:
    predictor:
      custom:
        container:
          image: accraze/outlink-topic-model
          name: kfserving-container
          env:
            - name: STORAGE_URI
              value: "s3://wmf-ml-models/outlinks-topic-model/202105251012/"
