# Apache config for Lift Wing OpenAPI specs
<VirtualHost *:8080>
    ServerName liftwing-openapi-server.discovery.wmnet
    ServerAlias api.wikimedia.org
    ServerAdmin noc@wikimedia.org
    ServerSignature On

    DocumentRoot /srv/app/docs

    LogLevel warn
    ErrorLog /dev/stderr

    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>

    <Directory /srv/app/docs>
        AllowOverride None
        Require all granted
    </Directory>

    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, OPTIONS"
    Header set Access-Control-Allow-Headers "*"
</VirtualHost>
