apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: enwiki-goodfaith
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    containers:
      - name: kfserving-container
        image: docker-registry.wikimedia.org/wikimedia/machinelearning-liftwing-inference-services-editquality:2021-07-28-204847-production
        env:
          # TODO: https://phabricator.wikimedia.org/T284091
          - name: STORAGE_URI
            value: "s3://wmf-ml-models/goodfaith/enwiki/202105132212/"
          - name: INFERENCE_NAME
            value: "enwiki-goodfaith"
          # WIKI_URL may be an internet routable endpoint (for example,
          # en.wikipedia.org) or an internal endpoint. In the latter use case
          # the WIKI_HOST variable is needed to populate the HTTP Host header.
          # Last but not least, REQUESTS_CA_BUNDLE may be added to trust a TLS
          # certificate signed by a private/internal CA.
          - name: WIKI_URL
            value: "https://api-ro.discovery.wmnet"
          - name: WIKI_HOST
            value: "en.wikipedia.org"
          - name: REQUESTS_CA_BUNDLE
            value: /usr/share/ca-certificates/wikimedia/Puppet_Internal_CA.crt

