openapi: "3.0.0"
info:
  title: Translation Recommendation — Lift Wing inference service
  version: v1
servers:
  - url: https://api.wikimedia.org
paths:
  /service/lw/recommendation/api/v1/translation:
    get:
      summary: Recommend content to translate
      description: |
        Get recommendations for Wikipedia articles to translate based on articles that exist in a source
        language wiki but are missing from a target language wiki.
      operationId: translation
      tags:
        - Countries, language, and translation
      parameters:
        - name: source
          in: query
          required: true
          schema:
            type: string
            example: "en"
          description: Source wiki language code
        - name: target
          in: query
          required: true
          schema:
            type: string
            example: "fr"
          description: Target wiki language code
        - name: count
          in: query
          required: false
          schema:
            type: integer
            default: 12
            example: 3
          description: Number of recommendations to fetch
        - name: seed
          in: query
          required: false
          schema:
            type: string
            nullable: true
            example: Apple
          description: One or more seed articles for personalized recommendations, separated by `|`
        - name: topic
          in: query
          required: false
          schema:
            type: string
            nullable: true
          description: One or more article topics for personalized recommendations, separated by `|`
        - name: country
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: featured_collection
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: collections
          in: query
          required: false
          schema:
            type: boolean
        - name: lead_section
          in: query
          required: false
          schema:
            type: boolean
        - name: include_pageviews
          in: query
          required: false
          schema:
            type: boolean
          description: Whether to include pageview counts in the response
        - name: search_algorithm
          in: query
          required: false
          schema:
            type: string
            enum:
              - morelike
              - mostpopular
            default: morelike
          description: Which search algorithm to use
        - name: rank_method
          in: query
          required: false
          schema:
            type: string
            enum:
              - default
              - sitelinks
            default: default
          description: Which rank method to use
        - name: min_size
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: max_size
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: continue_offset
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: continue_seed
          in: query
          required: false
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - recommendations
                properties:
                  recommendations:
                    type: array
                    items:
                      type: object
                      required:
                        - title
                      properties:
                        title:
                          type: string
                          description: Article title
                          example: Citrus australasica
                        pageviews:
                          type: integer
                          description: Number of page views
                          nullable: true
                          example: 0
                        wikidata_id:
                          type: string
                          description: Wikidata QID of the article
                          nullable: true
                          example: Q50837145
                        rank:
                          type: integer
                          nullable: true
                          example: 273
                        langlinks_count:
                          type: integer
                          nullable: true
                          example: 20
                        size:
                          type: integer
                          nullable: true
                          description: Article size in bytes
                          example: 15698
                        lead_section_size:
                          type: integer
                          nullable: true
                          description: Lead section size in bytes
                          example: 134
                        collection:
                          nullable: true
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            description:
                              type: string
                              nullable: true
                            end_date:
                              type: string
                              nullable: true
                            articles_count:
                              type: integer
                              nullable: true
                            articles_by_language_count:
                              type: object
                              nullable: true
                  continue_offset:
                    type: integer
                    nullable: true
                  continue_seed:
                    type: integer
                    nullable: true
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      required:
                        - loc
                        - msg
                        - type
                      properties:
                        loc:
                          type: array
                          items:
                            anyOf:
                              - type: string
                              - type: integer
                        msg:
                          type: string
                        type:
                          type: string
